### ISSUE TITLE
Error when loading existing games and available ones.

### ISSUE THREAD

**Issue by GGProGaming** [skrimix/QLoaderFiles#13]
Failed to refresh installed games
QSideloader.Services.DownloaderServiceException: Error downloading game list
 --- QSideloader.Services.DownloaderServiceException: No mirrors available for this session
   at QSideloader.Services.DownloaderService.SwitchMirror() in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 263
   at QSideloader.Services.DownloaderService.EnsureMirrorSelected() in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 328
   at QSideloader.Services.DownloaderService.EnsureMetadataAvailableAsync(Boolean refresh) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 467
   --- End of inner exception stack trace ---
   at QSideloader.Services.DownloaderService.EnsureMetadataAvailableAsync(Boolean refresh) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 505
   at QSideloader.Services.AdbService.AdbDevice.RefreshInstalledGames() in /home/runner/work/QLoader/QLoader/QSideloader/Services/AdbService.cs:line 1004

**Comment by skrimix** [comment]
Everything is up and running now, you just need to update to v0.2.5
