### ISSUE TITLE
Popularity data won't load

### ISSUE THREAD

**Issue by sjclayton** [skrimix/QLoaderFiles#16]
Getting this error message the last couple days out of nowhere, on Arch Linux with version 0.2.5

Failed to load popularity data
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Max[TSource](IEnumerable1 source, Func2 selector)
   at QSideloader.Services.DownloaderService.EnsureMetadataAvailableAsyncg__TryLoadPopularityAsync59_1() in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 596

**Comment by skrimix** [comment]
Is this still an issue?  It might happen sometimes, but shouldn't happen too frequently
