### ISSUE TITLE
Black screen in xwayland

### ISSUE THREAD

**Issue by gibarel1** [skrimix/QLoaderFiles#17]
Using wayland/xwayland the app is just a black screen and will not close, had to kill the process (clicking the "x" button does nothing).

**Log:**
```
 ╭─gibarel@gabriel in ~/QLoader/Loader
 ╰─λ ./Loader
[20:40:54 INF] ----------------------------------------
[20:40:54 INF] Starting Loader v0.2.5-beta...
[20:40:56 DBG] Refreshing backup list
[20:40:56 DBG] Started device monitor
[20:40:56 INF] Searching for devices
[20:40:56 WRN] No ADB devices found
[20:40:56 WRN] DeviceInfoViewModel.RefreshDeviceInfo: no device connection!
[20:40:56 INF] Searching for devices
[20:40:56 WRN] No ADB devices found
[20:40:56 DBG] Navigating to InstalledGamesView
[20:40:57 INF] Searching for devices
[20:40:57 WRN] No ADB devices found
[20:40:57 WRN] InstalledGamesViewModel.RefreshInstalledGames: no device connection!
[20:40:57 INF] Initializing updater
[20:40:59 INF] Excluded 7 dead mirrors for this session
[20:40:59 DBG] Loaded mirrors: ["FFA-04", "FFA-06", "FFA-07"]
[20:40:59 INF] Selected mirror: FFA-04
[20:40:59 INF] Updating rclone config
[20:41:03 INF] Rclone copyto "FFA-04:Quest Games/.meta/FFA" -> "./tools/linux/x64/rclone/FFA_config_new" completed in 4414.0 ms
[20:41:03 INF] Rclone config updated from FFA-04
[20:41:03 DBG] Loaded mirrors: ["FFA-04", "FFA-06", "FFA-07"]
[20:41:03 INF] Reloading mirror list completed in 327.5 ms
[20:41:03 INF] Downloading game list
[20:41:07 WRN] Rclone copyto "FFA-04:Quest Games/FFA.txt" -> "./metadata/FFA_new.txt" abandoned in 3535.2 ms
CliWrap.Exceptions.CommandExecutionException: Underlying process reported a non-zero exit code (1).

Command:
  ./tools/linux/x64/rclone/FFA copyto --retries 1  "FFA-04:Quest Games/FFA.txt" "./metadata/FFA_new.txt"

Standard error:
  <3>ERROR : FFA.txt: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
<3>ERROR : Attempt 1/1 failed with 1 errors and: failed to open source object: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
Failed to copyto: failed to open source object: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded

You can suppress this validation by calling `WithValidation(CommandResultValidation.None)` on the command.
   at CliWrap.Buffered.BufferedCommandExtensions.<>c__DisplayClass0_0.<ExecuteBufferedAsync>b__0(CommandResult r) in D:\a\CliWrap\CliWrap\CliWrap\Buffered\BufferedCommandExtensions.cs:line 62
   at CliWrap.Utils.Extensions.AsyncExtensions.Select[TSource,TDestination](Task`1 task, Func`2 transform) in D:\a\CliWrap\CliWrap\CliWrap\Utils\Extensions\AsyncExtensions.cs:line 14
   at QSideloader.Services.DownloaderService.RcloneTransferInternalAsync(String source, String destination, String operation, String additionalArgs, Int32 retries, CancellationToken ct) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 458
[20:41:07 DBG] Quota exceeded on game list FFA.txt on mirror FFA-04
[20:41:07 INF] Excluding mirror FFA-04 for this session
[20:41:07 INF] Selected mirror: FFA-07
[20:41:11 INF] Rclone copyto "FFA-07:Quest Games/FFA.txt" -> "./metadata/FFA_new.txt" completed in 3947.8 ms
[20:41:11 INF] Loaded 881 games
[20:41:12 INF] Requesting popularity from API completed in 767.1 ms
[20:41:12 INF] Loaded popularity data
[20:41:17 INF] Rclone copyto "FFA-07:Quest Games/.meta/nouns/blacklist.txt" -> "./metadata/blacklist_new.txt" completed in 4794.4 ms
[20:41:17 DBG] Downloaded donation blacklist
[20:41:17 DBG] Loaded 5195 blacklisted packages
[20:41:17 INF] Starting resource update in background
[20:41:17 DBG] Updating thumbnails (async)
[20:41:17 DBG] Updating trailers (async)
[20:41:21 INF] Rclone sync "FFA-07:Quest Games/.meta/videos/" -> "Resources/videos" completed in 4151.3 ms
[20:41:22 INF] Rclone sync "FFA-07:Quest Games/.meta/thumbnails/" -> "Resources/thumbnails" completed in 4913.0 ms
[20:41:22 INF] Finished resource update
```

**Specs:**
Garuda linux (arch based)
2080 super (up to date proprietary drivers)
kernel 6.0.5 zen
qloader version: i tried an older beta version i had and the latest v0.2.5 both with the same issue.
DE: plasma 5.26.2 wayland (kwin)

**Print:**
![loader](https://user-images.githubusercontent.com/21283067/200090352-1e2e32a9-9b60-414b-9213-57c1ff0d8ccc.png)

**It works fine under x11**

**Comment by skrimix** [comment]
Not sure what's wrong here exactly. I was able to reproduce the issue on a similar setup and it looks like some sort of incompatibility between AvaloniaUI and Wayland (or plasma on Wayland specifically?).
I don't have time to investigate this further, so for now you can try using [this CI build](https://drive.google.com/file/d/1t9MQ2KM7iQ1p4RHhfCWBhEzZx2zfx2Fx/view?usp=drivesdk) with --disable-gpu argument to force software rendering.

Btw this app doesn't use electron, so this has nothing to do with it.
