### ISSUE TITLE
No mirrors available for all downloads

### ISSUE THREAD

**Issue by mlsem** [skrimix/QLoaderFiles#18]
I im getting this error with many downloads

Log : 
Task Nock failed
QSideloader.Services.DownloaderServiceException: Error downloading release
 --- QSideloader.Services.DownloaderServiceException: No mirrors available for this download
   at QSideloader.Services.DownloaderService.SwitchMirror(IList1 mirrorList) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 352
   at QSideloader.Services.DownloaderService.DownloadGameAsync(Game game, CancellationToken ct) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 694
   --- End of inner exception stack trace ---
   at QSideloader.Services.DownloaderService.DownloadGameAsync(Game game, CancellationToken ct) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 705
   at QSideloader.ViewModels.TaskViewModel.DownloadAsync() in /home/runner/work/QLoader/QLoader/QSideloader/ViewModels/TaskViewModel.cs:line 356
   at QSideloader.ViewModels.TaskViewModel.RunDownloadAndInstallAsyncb__48_0() in /home/runner/work/QLoader/QLoader/QSideloader/ViewModels/TaskViewModel.cs:line 195
   at QSideloader.ViewModels.TaskViewModel.DoCancellableAsync(Func1 func, String failureStatus, String successStatus) in /home/runner/work/QLoader/QLoader/QSideloader/ViewModels/TaskViewModel.cs:line 324

**Comment by skrimix** [comment]
That means download quota is exceeded for those games. Nothing we can do, you just have to wait for some time (usually a few hours) and try again

**Comment by harryeffinpotter** [comment]
This means exactly what it says it means.
