### ISSUE TITLE
Failed to start ADB server error on start

### ISSUE THREAD

**Issue by KonstantinStarovoytov** [skrimix/QLoaderFiles#21]
Hi, I get error on start and can't connect my headset after loader update

Loader - v0.2.6-beta
MacOS Ventura 13.0.1
**log:** 

Failed to start ADB server

CliWrap.Exceptions.CommandExecutionException: Underlying process reported a non-zero exit code (137).

Command:
  ./tools/darwin/platform-tools/adb start-server

Standard error:
  

You can suppress this validation by calling WithValidation(CommandResultValidation.None) on the command.
   at CliWrap.Buffered.BufferedCommandExtensions.c__DisplayClass0_0.ExecuteBufferedAsyncb__0(CommandResult r) in D:\a\CliWrap\CliWrap\CliWrap\Buffered\BufferedCommandExtensions.cs:line 62
   at CliWrap.Utils.Extensions.AsyncExtensions.Select[TSource,TDestination](Task1 task, Func2 transform) in D:\a\CliWrap\CliWrap\CliWrap\Utils\Extensions\AsyncExtensions.cs:line 14
   at QSideloader.Services.AdbService.EnsureADBRunning() in /home/runner/work/QLoader/QLoader/QSideloader/Services/AdbService.cs:line 336

App Version: v0.2.6-beta
OS: OSX Unix 13.0.1

**installation id** - f8946745-144e-4bf2-b77c-9d3c66da037b

**Comment by elijajha20** [comment]
I have the same thing too but I'm on linux
Error refreshing installed games

QSideloader.Services.DownloaderServiceException: Error downloading game list
 --- QSideloader.Services.NoMirrorsAvailableException: No mirrors available for this session (8 excluded)
   at QSideloader.Services.DownloaderService.EnsureMirrorListInitialized() in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 413
   at QSideloader.Services.DownloaderService.EnsureMirrorSelected() in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 377
   at QSideloader.Services.DownloaderService.EnsureMetadataAvailableAsync(Boolean refresh) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 527
   --- End of inner exception stack trace ---
   at QSideloader.Services.DownloaderService.EnsureMetadataAvailableAsync(Boolean refresh) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 565
   at QSideloader.Services.AdbService.AdbDevice.RefreshInstalledGames() in /home/runner/work/QLoader/QLoader/QSideloader/Services/AdbService.cs:line 1013

App Version: v0.2.6-beta
OS: Linux Unix 5.10.142.19743
