### ISSUE TITLE
Cannot launch the program.

### ISSUE THREAD

**Issue by retta1** [skrimix/QLoaderFiles#22]
2022-11-27 04:53:40.792 +03:00 [INF] ----------------------------------------
2022-11-27 04:53:40.809 +03:00 [INF] Starting QLoader v0.2.6-beta...
2022-11-27 04:53:41.534 +03:00 [FTL] ------APPLICATION CRASH------
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string 'INFİNİTE' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.UInt64.Parse(String s, IFormatProvider provider)
   at Avalonia.Animation.IterationCount.Parse(String s) in /_/src/Avalonia.Animation/IterationCount.cs:line 167
   at Avalonia.Animation.Animation.set_RepeatCount(String value) in /_/src/Avalonia.Animation/Animation.cs:line 188
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Controls/ProgressRing.xaml(IServiceProvider, Styles)
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Controls/ProgressRing.xaml(IServiceProvider)
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String)
   at InvokeStub_!XamlLoader.TryLoad(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 57
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 89
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 91
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Application.Avalonia.Controls.IResourceNode.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Controls/Application.cs:line 201
   at Avalonia.Markup.Xaml.MarkupExtensions.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider) in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs:line 48
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Controls/RibbonStyles.xaml(IServiceProvider, Styles)
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Controls/RibbonStyles.xaml(IServiceProvider)
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String)
   at InvokeStub_!XamlLoader.TryLoad(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 57
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 89
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 91
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Application.Avalonia.Controls.IResourceNode.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Controls/Application.cs:line 201
   at Avalonia.Markup.Xaml.MarkupExtensions.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider) in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs:line 48
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Controls/RadialSlider.xaml(IServiceProvider, Styles)
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Controls/RadialSlider.xaml(IServiceProvider)
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String)
   at InvokeStub_!XamlLoader.TryLoad(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 57
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 89
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 91
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Application.Avalonia.Controls.IResourceNode.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Controls/Application.cs:line 201
   at Avalonia.Controls.ResourceNodeExtensions.TryFindResource(IResourceHost control, Object key, Object& value) in /_/src/Avalonia.Styling/Controls/ResourceNodeExtensions.cs:line 49
   at Avalonia.Controls.ResourceNodeExtensions.FindResource(IResourceHost control, Object key) in /_/src/Avalonia.Styling/Controls/ResourceNodeExtensions.cs:line 23
   at Avalonia.Controls.ResourceNodeExtensions.FloatingResourceObservable.PublishNext() in /_/src/Avalonia.Styling/Controls/ResourceNodeExtensions.cs:line 158
   at Avalonia.Controls.ResourceNodeExtensions.FloatingResourceObservable.ResourcesChanged(Object sender, ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/Controls/ResourceNodeExtensions.cs:line 181
   at Avalonia.Application.Avalonia.Controls.IResourceHost.NotifyHostedResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Controls/Application.cs:line 208
   at Avalonia.Controls.ResourceDictionary.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Controls/ResourceDictionary.cs:line 150
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 234
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 240
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 240
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 289
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 687
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
   at QSideloader.App.!XamlIlPopulate(IServiceProvider, App) in /home/runner/work/QLoader/QLoader/QSideloader/App.axaml:line 13
   at QSideloader.App.!XamlIlPopulateTrampoline(App)
   at QSideloader.App.Initialize() in /home/runner/work/QLoader/QLoader/QSideloader/App.axaml.cs:line 40
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 310
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at QSideloader.Program.Main(String[] args) in /home/runner/work/QLoader/QLoader/QSideloader/Program.cs:line 21

**Comment by phazei** [comment]
I can't launch it either, different error though.
```
[21:53:50 ERR] Error downloading game list
QSideloader.Services.NoMirrorsAvailableException: No mirrors available for this session (13 excluded)
   at QSideloader.Services.DownloaderService.SwitchMirror() in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 308
   at QSideloader.Services.DownloaderService.EnsureMirrorSelected() in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 380
   at QSideloader.Services.DownloaderService.EnsureMetadataAvailableAsync(Boolean refresh) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 527
```

Does that for every mirror.  Then just continually shows:
```
[21:56:16 DBG] Refreshing device info completed in 53.3 ms
[21:59:16 DBG] Refreshing device info completed in 68.5 ms
[22:02:16 DBG] Refreshing device info completed in 52.7 ms
[22:05:16 DBG] Refreshing device info completed in 63.2 ms
```
every few min.

Is it possible to make it openable without mirrors?  It still lists apps installed, backs up, and installs on MacOS.  Will there be future mirrors?  Is this project dead if FFA is dead?
