### ISSUE TITLE
I can't see anything on the mirror or on the available games

### ISSUE THREAD

**Issue by elijajha20** [skrimix/QLoaderFiles#23]
Once I downloaded the new update nothing works it has an error code too
Error refreshing installed games

QSideloader.Services.DownloaderServiceException: Error downloading game list
 --- QSideloader.Services.NoMirrorsAvailableException: No mirrors available for this session (8 excluded)
   at QSideloader.Services.DownloaderService.EnsureMirrorListInitialized() in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 413
   at QSideloader.Services.DownloaderService.EnsureMirrorSelected() in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 377
   at QSideloader.Services.DownloaderService.EnsureMetadataAvailableAsync(Boolean refresh) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 527
   --- End of inner exception stack trace ---
   at QSideloader.Services.DownloaderService.EnsureMetadataAvailableAsync(Boolean refresh) in /home/runner/work/QLoader/QLoader/QSideloader/Services/DownloaderService.cs:line 565
   at QSideloader.Services.AdbService.AdbDevice.RefreshInstalledGames() in /home/runner/work/QLoader/QLoader/QSideloader/Services/AdbService.cs:line 1013

App Version: v0.2.6-beta
OS: Linux Unix 5.10.142.19743

**Comment by skrimix** [comment]
FFA have shut down, online functionality doesn't work anymore.
The announcement can be found [here](https://t.me/FFA_Feed/2960)
